### ISSUE TITLE
NONE OF THIS ACTUALLY WORKS!!!

### ISSUE THREAD

**Issue by chunkybanana** [belen-albeza/retro-canvas#3]
This only appears to work because the image shown is the same size as the canvas, so the pixels are drawn correctly. Substitute cat.png for ANY image smaller than 128x128 and the image will blur, no matter what image-rendering is set to.

**Comment by chunkybanana** [comment]
After some research, I've figured out how you can make canvas images properly pixelated: Use the context's imageSmoothingEnabled property (appropriately prefixed). [Demo](https://www.w3schools.com/code/tryit.asp?filename=GKPYERJCTE09). Please fix this.

**Comment by belen-albeza** [comment]
I'm not accepting this language and behavior in my repos. Specially those repos who haven't been maintained over _five_ years, and I keep online only for archival reasons.
